### ISSUE TITLE
vuex dependencies are missing

### ISSUE THREAD

**Issue by mrflos** [p-adams/simple-todo-tutorial#1]
Hi, just tried to launch this demo and after cloning repo, `npm install` and `npm run dev`
I had an error about vuex missing.  
I tried to install it with `npm install vuex` but the server localhost:8080 is a blank page now.

**Comment by p-adams** [comment]
Hi, 

Did you run `npm install vuex@next` ? `npm install vuex` will install 1.0 so some of the newer features such as `this.$store.getters.todos` won't work. I just tried it by installing `vuex@next` and it worked. Sorry about that.

**Comment by mrflos** [comment]
Thanks a lot, I did'nt know about this @next, very usefull for testing!  

And your article was a nice reading too!
