### ISSUE TITLE
Doesn't work with latest webpack-dev-server

### ISSUE THREAD

**Issue by builtbyka** [p-adams/simple-todo-tutorial#3]
Hi there

Thank you so much for this tutorial and demo pack. 

I just wanted to let you know, I tried installing the pack and found that the latest version of webpack-dev-server (2.1.0-beta.9) throws the error 

WebpackOptionsValidationError: Invalid configuration object

By rolling the version of webpack-dev-server back it worked fine (I got the idea from here https://github.com/AngularClass/angular2-webpack-starter/issues/1036) but thought I better flag it in case you have anyone else with this issue!

**Comment by p-adams** [comment]
Thanks!

**Comment by cschweda** [comment]
I commented out this line in webpack.config.js:

`
resolveLoader: {
    root: path.join(__dirname, 'node_modules'),
  },
`

App runs without error.
